# Konfigurasi jaringan dan interface
interface: "eth0"

# Pengaturan iptables
forward_chain: "FORWARD"
block_time_sec: 600          # Durasi pemblokiran IP dalam detik

# Rate limiting dan window waktu analisis
rate_limit_count: 200        # Maks paket per IP per window waktu
rate_limit_window: 10        # Window waktu per hitungan paket dalam detik

# Scrubbing server IP untuk redirect trafik berbahaya
scrubbing_center_ip: "10.0.0.200"

# Backup configuration
backup_source: "/data/production/"
backup_target: "/backups/production/"
backup_interval: 3600        # Interval backup otomatis dalam detik (default 1 jam)

# Machine Learning (ML) konfigurasi
ml_contamination: 0.02       # Persentase estimasi outlier pada dataset ML
ml_training_samples: 100     # Jumlah sampel untuk pelatihan awal model ML

# Direktori yang dipantau untuk deteksi ransomware berbasis filesystem changes
monitored_dirs:
  - "/data/production"

# Logging konfigurasi
log_file: "security_monitor.log"
log_max_bytes: 10485760      # 10 MB
log_backup_count: 5          # Backup file rotasi, total 5 file maksimum

# Jumlah worker multiprocessing untuk pemrosesan paket
worker_process_count: 4
